config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'index/index'
  get 'demo' => 'index#demo'

  get 'index/test'
  post 'index/test'

  get 'about' => 'index#about', as: :about
  get 'dashboard' => 'index#index', as: :dashboard

  get 'project/:project_id/members' => 'members#index', as: :project_members
  get 'project/:project_id/members/new' => 'members#new', as: :new_project_member
  post 'project/:project_id/members/add' => 'members#add', as: :add_project_member
  delete 'project/:project_id/members/:id/remove' => 'members#destroy', as: :project_remove_member

  post 'members/:member_id/toggle_is_scholar' => 'members#toggle_is_scholar', as: :toggle_is_scholar
  post 'members/:member_id/toggle_is_manager' => 'members#toggle_is_manager', as: :toggle_is_manager

  get 'project/:project_id/tasks' => 'tasks#index', as: :project_task
  get 'project/:project_id/tasks/new' => 'tasks#new', as: :new_project_task
  get 'project/:project_id/tasks/:id/edit' => 'tasks#edit', as: :edit_project_task
  post 'project/:project_id/tasks/create' => 'tasks#create', as: :create_project_task
  delete 'project/:project_id/tasks/:id/remove' => 'tasks#destroy', as: :project_remove_task
  get 'tasks/:id/member/new' => 'tasks#new_member', as: :new_task_member
  post 'tasks/:id/member/:user_id/add' => 'tasks#add_member', as: :add_task_member
  delete 'tasks/:id/member/:member_id/remove' => 'tasks#remove_member', as: :task_remove_member

  delete 'events/:id/user/:user_id/remove' => 'events#remove_user', as: :event_remove_user
  get 'events/:id/user/new' => 'events#new_user', as: :new_event_user
  post 'events/:id/user/:user_id/add' => 'events#add_user', as: :add_event_user

  post 'tasks/:id/add_comment' => 'tasks#add_comment', as: :task_add_comment

  resources :projects
  resources :members
  resources :tasks
  resources :events
  resources :users

  root 'index#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :members

  validates :title, :description, presence: true

  self.per_page = 10


  def add_member(user, attributes={})
    if self.members.include?(user) or not self.project.users.include?(user)
      false
    else
      self.members << Member.where(project_id: self.project_id, user_id: user.id)
    end
  end

  def add_comment(attributes={})
      self.comments << Comment.create(member_id: attributes[:member_id], task_id: self.id, title: attributes[:title], content: attributes[:content])
  end

  def set_project(project, attributes={})
    self.project = project
  end

  def self.done_list(user, project)
    if project == nil
      Task.joins(:members)
          .where("members.user_id = #{user.id} AND tasks.status = 'Concluída'")
          .order("due_date asc")
    else
      Task.where("tasks.project_id = #{project.id} AND tasks.status = 'Concluída'")
          .order("due_date asc")

    end
  end

  def self.pending_list(user, project)
    if project == nil
      Task.joins(:members)
          .where("members.user_id = #{user.id} AND tasks.status = 'Pendente'")
          .order("due_date asc")
    else
      Task.where("tasks.project_id = #{project.id} AND tasks.status = 'Pendente'")
          .order("due_date asc")
    end
  end

  def self.in_progress_list(user, project)
    if project == nil
      Task.joins(:members)
          .where("members.user_id = #{user.id} AND tasks.status = 'Em andamento'")
          .order("due_date asc")
    else
      Task.where("tasks.project_id = #{project.id} AND tasks.status = 'Em andamento'")
          .order("due_date asc")
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :new_member, :add_member, :remove_member]

  # GET /tasks
  # GET /tasks.json
  def index
     @tasks_done = Task.done_list(current_user, nil)
     @tasks_in_progress = Task.in_progress_list(current_user, nil)
     @tasks_pending = Task.pending_list(current_user, nil)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @project = Project.find params[:project_id]
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find params[:project_id]
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        @task.add_member(current_user)
        format.html { redirect_to @task, notice: 'Tarefa criada com sucesso.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # POST /task/1/add_comment
  def add_comment
       @task = Task.find params[:id]
       member = Member.where(project_id: @task.project_id, user_id: current_user.id).first
       @task.add_comment(title: params[:title], content: params[:content], member_id: member.id)
       redirect_to task_path(@task), notice: "Comentário adicionado"
  end

  # GET /tasks/1/member/new
  def new_member
    @query = params['query']
    @users = User.select("users.id, users.name, users.email, users.university")
                    .joins(:members)
                    .where('members.project_id': @task.project_id)
                    .where.not('members.id' => MemberTask.select('member_id').where(task_id: @task.id))
    if @query.present?
      @users = @users.text_search(@query)
    end
  end

  # POST /tasks/1/member/1/add
  def add_member
    user = User.find params[:user_id]
    @task.add_member(user)
    respond_to do |format|
      format.html { redirect_to task_path(params[:id]), notice: user.name + " adicionado à tarefa " + @task.title + " com sucesso."}
      format.json { head :no_content }
    end
  end

  # DELETE /tasks/1/member/1/remove
  def remove_member
    member = Member.find params[:member_id]
    @task.members.delete(member)

    respond_to do |format|
      format.html { redirect_to task_path(@task), notice: "#{member.user.name} foi removido da tarefa com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :status, :project_id)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>

  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select([["Selecionar estado", ""], "Pendente", "Em andamento", "Concluída"], @task.status), :class => 'form_control' %>
  </div>

  <%= f.hidden_field :project_id, :value => @project.id %>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary bt-show" %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Editar Tarefa" %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<p>
  <%= button_to "Detalhes do Tarefa", @task, :class => "btn btn-primary bt-show", :method => :get %>
  <%= button_to "Detalhes do Projeto", project_url(@project), :class => "btn btn-primary bt-show", :method => :get %>
</p>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do projeto
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                  <%= render 'form' %>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/tasks/index.html.erb
<%- model_class = Task -%>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Suas tarefas pendentes
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:id) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:title) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:description) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:due_date) %></th>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:status) %></th>
                                <th class="col-xs-3">Projeto</th>
                                <th class="col-xs-1">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @tasks_pending.each do |task| %>
                            <tr>
                              <td><%= task.id %></td>
                              <td><%= task.title %></td>
                              <td><%= task.description %></td>
                              <td><%= I18n.l task.due_date, format: :short %></td>
                              <td><%= task.status %></td>
                              <td><%= task.project.name %></td>
                              <td>
                                <%= link_to task do %>
                                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                <% end %>
                                <%= link_to edit_project_task_path(task.project, task) do %>
                                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                <% end %>
                                    <%= link_to task, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Suas tarefas em andamento
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:id) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:title) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:description) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:due_date) %></th>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:status) %></th>
                                <th class="col-xs-3">Projeto</th>
                                <th class="col-xs-1">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @tasks_in_progress.each do |task| %>
                            <tr>
                              <td><%= task.id %></td>
                              <td><%= task.title %></td>
                              <td><%= task.description %></td>
                              <td><%= I18n.l task.due_date, format: :short %></td>
                              <td><%= task.status %></td>
                              <td><%= task.project.name %></td>
                              <td>
                                <%= link_to task do %>
                                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                <% end %>
                                <%= link_to edit_project_task_path(task.project, task) do %>
                                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                <% end %>
                                    <%= link_to task, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Suas tarefas concluídas
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:id) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:title) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:description) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:due_date) %></th>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:status) %></th>
                                <th class="col-xs-3">Projeto</th>
                                <th class="col-xs-1">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @tasks_done.each do |task| %>
                            <tr>
                              <td><%= task.id %></td>
                              <td><%= task.title %></td>
                              <td><%= task.description %></td>
                              <td><%= I18n.l task.due_date, format: :short %></td>
                              <td><%= task.status %></td>
                              <td><%= task.project.name %></td>
                              <td>
                                <%= link_to task do %>
                                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                <% end %>
                                <%= link_to edit_project_task_path(task.project, task) do %>
                                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                <% end %>
                                    <%= link_to task, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Criar Tarefa" %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= button_to "Voltar", project_url(@project), :class => "btn btn-primary bt-show", :method => :get %>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Informações da tarefa
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                  <%= render 'form' %>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/tasks/new_member.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Adicionar Membro à Tarefa" %></h1>
    <%= button_to "Voltar", task_path(@task), :class => "btn btn-primary bt-show", :method => :get %>
  </div>
  <!-- /.col-lg-12 -->
</div>

<br>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Procurar membro para adicionar
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <%= form_tag new_task_member_path(@task), method: :get do %>
                  <div class="input-group custom-search-form">
                      <%= text_field_tag :query, @query, class: "form-control", placeholder: "Pesquisar por nome, e-mail ou instituição" %>
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                          <i class="fa fa-search"></i>
                        </button>
                      </span>
                  </div>
                <% end %>
                <br>

                <% if not @users.empty? %>

                  <div class="table-responsive">
                      <table class="table table-striped table-bordered table-hover">
                        <thead>
                          <tr>
                            <th class="col-xs-1">Cód.</th>
                            <th class="col-xs-5">Nome</th>
                            <th class="col-xs-3">E-mail</th>
                            <th class="col-xs-2">Instituição</th>
                            <th class="col-xs-1">Adicionar</th>
                          </tr>
                        </thead>

                        <tbody>

                          <% @users.each do |user| %>
                            <tr>
                              <td><%= user.id %></td>
                              <td><%= user.name %></td>
                              <td><%= user.email %></td>
                              <td><%= user.university %></td>
                              <%= form_tag add_task_member_path(@task, user), method: :post do %>
                                <td>
                                  <%= hidden_field_tag :user_id, user.id %>

                                  <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-plus"></i>
                                  </button>
                                </td>
                              <% end %>
                            </tr>
                          <% end %>


                        </tbody>
                      </table>
                  </div>
                  <!-- /.table-responsive -->
                <% end %>

                <% if @query.present? and @users.empty? %>
                  <div class="alert alert-warning" role="alert">Nenhum usuário encontrado</div>
                <% end %>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => 'Detalhes da Tarefa' %></h1>

    <%= button_to "Voltar", tasks_path, :class => "btn btn-primary bt-show", :method => :get %>
    <%= button_to "Editar Tarefa", edit_project_task_path(@task.project, @task), :class => "btn btn-primary bt-show", :method => :get %>
  </div>
  <!-- /.col-lg-12 -->
</div>

<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados da Tarefa
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <p>
                      <strong>Title:</strong>
                      <%= @task.title %>
                    </p>

                    <p>
                      <strong>Description:</strong>
                      <%= @task.description %>
                    </p>

                    <p>
                      <strong>Due date:</strong>
                      <%= @task.due_date %>
                    </p>

                    <p>
                      <strong>Status:</strong>
                      <%= @task.status %>
                    </p>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<div class="row">
  <div class="col-lg-12">
    <%= button_to "Adicionar Membro à Tarefa", new_task_member_path(@task), :class => "btn btn-primary bt-show", :method => :get %>
  </div>
  <!-- /.col-lg-12 -->
</div>

<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Membros nesta Tarefa
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                          <tr>
                            <th class="col-xs-1">Cód.</th>
                            <th class="col-xs-5">Nome</th>
                            <th class="col-xs-3">E-mail</th>
                            <th class="col-xs-2">Telefone</th>
                            <th class="col-xs-1">Apagar</th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @task.members.each do |member| %>
                            <tr>
                              <td><%= member.user.id %></td>
                              <td><%= member.user.name %></td>
                              <td><%= member.user.email %></td>
                              <td><%= member.user.phone %></td>
                              <td>
                                <%= link_to task_remove_member_path(@task, member), method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Comentários [<%= @task.comments.count %>]
            </div>

            <div class="panel-body">
              <div class="form-group">
                  <%= form_tag task_add_comment_path(), method: :post do %>
                  <input class="form-control" name="title" style="margin-bottom: 4px" placeholder="Título do comentário..."></input>
                  <textarea class="form-control" rows="3" name="content" placeholder="Seu comentário..."></textarea>
                  <%= hidden_field_tag :id, :value => @task.id %>
                  <button class="btn btn-primary comments-bt" type="submit">
                      Enviar
                  </button>
                  <% end %>
              </div>

                <% @task.comments.order("comments.created_at desc").each do |comment| %>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                        <%= comment.member.user.name %> (<%= I18n.l comment.created_at, format: :short %>):
                    </div>
                    <div class="panel-body">
                        <h4><%= comment.title %></h4>
                        <%= comment.content %>
                        <br>
                        <br>
                    </div>
                  </div>
                <% end %>

            </div>
        </div>
    </div>
</div>