config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'index/index'
  get 'demo' => 'index#demo'

  get 'index/test'
  post 'index/test'

  get 'about' => 'index#about', as: :about
  get 'dashboard' => 'index#index', as: :dashboard

  get 'project/:project_id/members' => 'members#index', as: :project_members
  get 'project/:project_id/members/new' => 'members#new', as: :new_project_member
  post 'project/:project_id/members/add' => 'members#add', as: :add_project_member
  delete 'project/:project_id/members/:id/remove' => 'members#destroy', as: :project_remove_member

  post 'members/:member_id/toggle_is_scholar' => 'members#toggle_is_scholar', as: :toggle_is_scholar
  post 'members/:member_id/toggle_is_manager' => 'members#toggle_is_manager', as: :toggle_is_manager

  get 'project/:project_id/tasks' => 'tasks#index', as: :project_task
  get 'project/:project_id/tasks/new' => 'tasks#new', as: :new_project_task
  get 'project/:project_id/tasks/:id/edit' => 'tasks#edit', as: :edit_project_task
  post 'project/:project_id/tasks/create' => 'tasks#create', as: :create_project_task
  delete 'project/:project_id/tasks/:id/remove' => 'tasks#destroy', as: :project_remove_task
  get 'tasks/:id/member/new' => 'tasks#new_member', as: :new_task_member
  post 'tasks/:id/member/:user_id/add' => 'tasks#add_member', as: :add_task_member
  delete 'tasks/:id/member/:member_id/remove' => 'tasks#remove_member', as: :task_remove_member

  delete 'events/:id/user/:user_id/remove' => 'events#remove_user', as: :event_remove_user
  get 'events/:id/user/new' => 'events#new_user', as: :new_event_user
  post 'events/:id/user/:user_id/add' => 'events#add_user', as: :add_event_user

  post 'tasks/:id/add_comment' => 'tasks#add_comment', as: :task_add_comment

  resources :projects
  resources :members
  resources :tasks
  resources :events
  resources :users

  root 'index#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  validates :title, :date, presence: true

  def add_user(user, attributes={})
  	if self.users.include?(user)
      false
    else
      self.users << user
    end
  end

  def remove_user(user)
  	self.users.delete(user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :new_user, :add_user, :remove_user]
  before_action :check_if_owner, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.joins(:events_users)
                   .where("events_users.user_id = #{current_user.id} OR events.is_private = false")
                   .order("date desc")
                   .paginate(:page => params[:page])
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @users = User.joins(:events).where(events_users: {event_id: @event.id})
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.owner = current_user

    respond_to do |format|
      if @event.save
        @event.add_user(current_user)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /events/1/user/new
  def new_user
    @query = params['query']
    if @query.present?
      @users = User.select("id, name, email, university")
                    .where.not(id: EventUser.select("user_id").where(event_id: @event.id))
                    .text_search(@query)
    else
      @users = []
    end
  end

  # POST /events/1/user/1/add
  def add_user
    user = User.find params[:user_id]
    @event.add_user(user)
    respond_to do |format|
      format.html { redirect_to event_path(@event), notice: user.name + " adicionado ao evento " + @event.title + " com sucesso." }
      format.json { head :no_content }
    end
  end

  # DELETE /events/1/user/1/remove
  def remove_user
    user = User.find params[:user_id]
    @event.remove_user(user)
    
    respond_to do |format|
      format.html { redirect_to event_path(@event), notice: "#{user.name} foi removido do evento com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :date, :location, :location_url, :kind, :is_private, :owner_id)
    end

    def check_if_owner
      unless current_user.owns_event?(@event)
        flash[:alert] = 'Você não tem permissão para isso'
        redirect_to events_path
      end
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location_url %><br>
    <%= f.text_field :location_url, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :kind %><br>
    <%= f.select :kind, options_for_select([["Selecionar tipo", ""], "Congresso", "Minicurso", "Palestra", "Reunião", "Workshop"], @event.kind), :class => 'form_control' %>
  </div>

  <div class="form-group">
    <%= f.label :is_private %> <%= f.check_box :is_private %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary bt-show" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Editar Evento" %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<p>
  <%= button_to "Detalhes do Evento", @event, :class => "btn btn-primary bt-show", :method => :get %>
  <%= button_to "Lista de Eventos", events_path, :class => "btn btn-primary bt-show", :method => :get %>
</p>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do projeto
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <%= render 'form' %>

                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<% if current_user.is_professor %>
    <%= link_to 'Novo ' + model_class.model_name.human.titleize, new_event_path, class: 'btn btn-primary lonely_button' %>
<% end %>

<div class="row projects_label">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Seus <%= model_class.model_name.human.pluralize.titleize %>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                          <tr>
                            <th class="col-xs-2"><%= model_class.human_attribute_name(:title) %></th>
                            <th class="col-xs-2"><%= model_class.human_attribute_name(:description) %></th>
                            <th class="col-xs-2"><%= model_class.human_attribute_name(:date) %></th>
                            <th class="col-xs-2"><%= model_class.human_attribute_name(:location) %></th>
                            <th class="col-xs-1"><%= model_class.human_attribute_name(:kind) %></th>
                            <th class="col-xs-1"><%= model_class.human_attribute_name(:is_private) %></th>
                            <th class="col-xs-1">Passou?</th>
                            <th class="col-xs-1">Ações</th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @events.each do |event| %>
                            <tr>
                              <td><%= event.title %></td>
                              <td><%= event.description %></td>
                              <td><%= I18n.l event.date, format: :short %></td>
                              <td><%= event.location %></td>
                              <td><%= event.kind %></td>
                              <td><%= (event.is_private ? "Sim" : "Não") %></td>
                              <td><%= (event.date.to_i < Time.now.to_i ? "Sim" : "Não" ) %></td>
                              <td>
                                <%= link_to event do %>
                                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                <% end %>
                                <% if current_user.owns_event?(event) %>
                                  <%= link_to edit_event_path(event) do %>
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                  <% end %>
                                  <% if current_user.is_professor %>
                                    <%= link_to event, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    <% end %>
                                  <% end %>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <div class="col-md-12 text-center"><%= will_paginate @events, renderer: BootstrapPagination::Rails %></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Criar Evento" %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= button_to "Voltar", events_path, :class => "btn btn-primary bt-show", :method => :get %>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do evento
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                      <%= render 'form' %>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/events/new_user.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Adicionar usuário ao evento" %></h1>
    <%= button_to "Voltar", event_path(@event), :class => "btn btn-primary bt-show", :method => :get %>
  </div>
  <!-- /.col-lg-12 -->
</div>

<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Procurar membro para adicionar
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <%= form_tag new_event_user_path(@event), method: :get do %>
                  <div class="input-group custom-search-form">
                      <%= text_field_tag :query, @query, class: "form-control", placeholder: "Pesquisar por nome, e-mail ou instituição" %>
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                          <i class="fa fa-search"></i>
                        </button>
                      </span>
                  </div>
                <% end %>
                <br>

                <% if @query.present? and not @users.empty? %>

                  <div class="table-responsive">
                      <table class="table table-striped table-bordered table-hover">
                        <thead>
                          <tr>
                            <th class="col-xs-1">Cód.</th>
                            <th class="col-xs-4">Nome</th>
                            <th class="col-xs-2">E-mail</th>
                            <th class="col-xs-2">Instituição</th>
                            <th class="col-xs-1">Adicionar</th>
                          </tr>
                        </thead>

                        <tbody>

                          <% @users.each do |user| %>
                            <tr>
                              <td><%= user.id %></td>
                              <td><%= user.name %></td>
                              <td><%= user.email %></td>
                              <td><%= user.university %></td>
                              <%= form_tag add_event_user_path(@event, user), method: :post do %>
                                <td>
                                  <%= hidden_field_tag :user_id, user.id %>

                                  <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-plus"></i>
                                  </button>
                                </td>
                              <% end %>
                            </tr>
                          <% end %>


                        </tbody>
                      </table>
                  </div>
                  <!-- /.table-responsive -->
                <% end %>

                <% if @query.present? and @users.empty? %>
                  <div class="alert alert-warning" role="alert">Nenhum usuário encontrado</div>
                <% end %>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/events/show.html.erb
<%- model_class = Event -%>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => @event.title %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= button_to "Voltar", events_path, :class => "btn btn-primary bt-show", :method => :get %>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do evento
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                      <p>
                        <strong>Descrição:</strong>
                        <%= @event.description %>
                      </p>

                      <p>
                        <strong>Data:</strong>
                        <%= I18n.l @event.date, format: :short %>
                      </p>

                      <p>
                        <strong>Local:</strong>
                        <%= @event.location %>
                        <% if not @event.location_url.blank? %>
                          &lt;<a href="http://<%= @event.location_url %>" target="_blank"><%= @event.location_url %></a>&gt;
                        <% end %>
                      </p>

                      <p>
                        <strong>Tipo de evento:</strong>
                        <%= @event.kind %>
                      </p>

                      <p>
                        <strong>Tipo de acesso:</strong>
                        <%= (@event.is_private)? "Privado" : "Público" %>
                      </p>
                      <% if current_user.owns_event?(@event) %>
                        <p>
                          <%= button_to "Editar", edit_event_path(@event), :class => "btn btn-primary bt-show", :method => :get %>
                        </p>
                      <% end %>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<% if @event.is_private %>
<div class="row">
  <div class="col-lg-12">
    <%= button_to "Adicionar Membro ao Evento", new_event_user_path(@event), :class => "btn btn-primary bt-show", :method => :get %>
  </div>
  <!-- /.col-lg-12 -->
</div>

<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Convidados para o evento
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                          <tr>
                            <th class="col-xs-1">Cód.</th>
                            <th class="col-xs-5">Nome</th>
                            <th class="col-xs-3">E-mail</th>
                            <th class="col-xs-1">Telefone</th>
                            <th class="col-xs-1">Universidade</th>
                            <th class="col-xs-1">Apagar</th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @users.each do |user| %>
                            <tr>
                              <td><%= user.id %></td>
                              <td><%= user.name %></td>
                              <td><%= user.email %></td>
                              <td><%= user.phone %></td>
                              <td><%= user.university %></td>
                              <td>
                                <%= link_to event_remove_user_path(@event, user), method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<% end %>