config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'index/index'
  get 'demo' => 'index#demo'

  get 'index/test'
  post 'index/test'

  get 'about' => 'index#about', as: :about
  get 'dashboard' => 'index#index', as: :dashboard

  get 'project/:project_id/members' => 'members#index', as: :project_members
  get 'project/:project_id/members/new' => 'members#new', as: :new_project_member
  post 'project/:project_id/members/add' => 'members#add', as: :add_project_member
  delete 'project/:project_id/members/:id/remove' => 'members#destroy', as: :project_remove_member

  post 'members/:member_id/toggle_is_scholar' => 'members#toggle_is_scholar', as: :toggle_is_scholar
  post 'members/:member_id/toggle_is_manager' => 'members#toggle_is_manager', as: :toggle_is_manager

  get 'project/:project_id/tasks' => 'tasks#index', as: :project_task
  get 'project/:project_id/tasks/new' => 'tasks#new', as: :new_project_task
  get 'project/:project_id/tasks/:id/edit' => 'tasks#edit', as: :edit_project_task
  post 'project/:project_id/tasks/create' => 'tasks#create', as: :create_project_task
  delete 'project/:project_id/tasks/:id/remove' => 'tasks#destroy', as: :project_remove_task
  get 'tasks/:id/member/new' => 'tasks#new_member', as: :new_task_member
  post 'tasks/:id/member/:user_id/add' => 'tasks#add_member', as: :add_task_member
  delete 'tasks/:id/member/:member_id/remove' => 'tasks#remove_member', as: :task_remove_member

  delete 'events/:id/user/:user_id/remove' => 'events#remove_user', as: :event_remove_user
  get 'events/:id/user/new' => 'events#new_user', as: :new_event_user
  post 'events/:id/user/:user_id/add' => 'events#add_user', as: :add_event_user

  post 'tasks/:id/add_comment' => 'tasks#add_comment', as: :task_add_comment

  resources :projects
  resources :members
  resources :tasks
  resources :events
  resources :users

  root 'index#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  include PgSearch
  
  after_create :init_last_update

  has_many :tasks
  has_many :members, dependent: :destroy
  has_many :users, through: :members

  self.per_page = 10

  validates :name, presence: true
  validates :name, uniqueness: true

  pg_search_scope :search, against: [:name, :description],
                  using: {tsearch: {dictionary: "portuguese"}},
                  ignoring: :accents


  def add_member(user, attributes={})
    if self.users.include?(user)
      false
    else
      self.members << Member.create(user: user, project: self, is_manager: attributes[:is_manager], is_scholar: attributes[:is_scholar])
    end
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      self.all
    end
  end

  private

  def init_last_update
    self.last_update = created_at
    self.save!
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_professor, only: [:new, :create]
  before_action :check_if_is_manager, only: [:edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    query = params['query']
    @projects = Project.text_search(query)
                        .joins(:members)
                        .where(members: {user_id: current_user.id})
                        .order("last_update desc")
                        .paginate(:page => params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks_in_progress = Task.in_progress_list(nil, @project)

    @tasks_done = Task.done_list(nil, @project)

    @tasks_pending = Task.pending_list(nil, @project)

    @tasks_total_count = (@tasks_in_progress.count + @tasks_pending.count + @tasks_done.count)
    if(@tasks_total_count > 0)
      @done_tasks_percentage = @tasks_done.count * 100 / @tasks_total_count
    else
      @done_tasks_percentage = 0
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        @project.add_member(current_user, is_manager: true, is_scholar: false)
        format.html { redirect_to @project, notice: 'Projeto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Projeto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Projeto foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :last_update)
    end

    def check_if_is_manager
      @project = Project.find(params[:id])
      unless current_user.is_manager?(@project)
        flash[:alert] = 'Você não tem permissão para isso'
        redirect_to projects_path
      end
    end

    def check_if_professor
      unless current_user.is_professor
        flash[:alert] = 'Você não tem permissão para isso'
        redirect_to projects_path
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary bt-show" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Editar Projeto" %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<p>
  <%= button_to "Detalhes do Projeto", @project, :class => "btn btn-primary bt-show", :method => :get %>
  <%= button_to "Lista de Projetos", projects_path, :class => "btn btn-primary bt-show", :method => :get %>
</p>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do projeto
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                  <%= render 'form' %>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/projects/index.html.erb
<%- model_class = Project -%>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-sm-3">
    <% if current_user.is_professor %>
      <%= link_to 'Novo ' + model_class.model_name.human.titleize, new_project_path, class: 'btn btn-primary lonely_button' %>
    <% end %>
  </div>

  <div class="col-sm-9">
    <%= form_tag projects_path, method: :get do %>
      <div class="input-group custom-search-form">
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Pesquisar projeto por nome" %>
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit">
              <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>

<div class="row projects_label">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= model_class.model_name.human.pluralize.titleize %> recentemente atualizados
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="col-xs-1"><%= model_class.human_attribute_name(:id) %></th>
                                <th class="col-xs-8"><%= model_class.human_attribute_name(:name) %></th>
                                <th class="col-xs-2"><%= model_class.human_attribute_name(:last_update) %></th>
                                <th class="col-xs-1">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                          <% @projects.each do |project| %>
                            <tr>
                              <td><%= project.id %></td>
                              <td><%= project.name %></td>
                              <td><%= I18n.l project.last_update, format: :short %></td>
                              <td>
                                <%= link_to project do %>
                                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                <% end %>
                                <% if current_user.is_manager?(project) %>
                                  <%= link_to edit_project_path(project) do %>
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                  <% end %>
                                  <%= link_to project, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                  <% end %>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <div class="col-md-12 text-center"><%= will_paginate @projects, renderer: BootstrapPagination::Rails %></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => "Criar Projeto" %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= button_to "Voltar", projects_path, :class => "btn btn-primary bt-show", :method => :get %>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do projeto
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                      <%= render 'form' %>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

app/views/projects/show.html.erb
<%- model_class = Task -%>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t '.title', :default => @project.name %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= button_to "Voltar", projects_path, :class => "btn btn-primary bt-show", :method => :get %>

<br>
<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dados do Projeto
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                      <p>
                        <strong>Descrição:</strong>
                        <%= @project.description %>
                      </p>

                      <p>
                        <strong>Número de membros:</strong>
                        <%= @project.members.count %>
                      </p>

                    <p>
                      <div>
                          <p>
                              <strong><%= @tasks_total_count - @tasks_done.count %> tarefa(s) em espera/andamento</strong>
                              <span class="pull-right text-muted"><%= @tasks_done.count %> tarefa(s) concluída(s)</span>
                          </p>
                          <div class="progress progress-striped active">
                              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @done_tasks_percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @done_tasks_percentage %>%">
                                  <span class="sr-only"><%= @done_tasks_percentage %>% Concluído (success)</span>
                              </div>
                          </div>
                      </div>
                    </p>

                      <p>
                        <% if current_user.is_manager?(@project) %>
                          <%= button_to "Editar", edit_project_path(@project), :class => "btn btn-primary bt-show", :method => :get %>
                          <%= button_to "Gerenciar Membros", project_members_path(@project), :class => "btn btn-primary bt-show", :method => :get %>
                        <% end %>
                      </p>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<br>
<%= link_to 'Adicionar ' + model_class.model_name.human.titleize, new_project_task_path(@project), class: 'btn btn-primary' %>
<br>
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= model_class.model_name.human.pluralize.titleize %> pendentes
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                      <thead>
                          <tr>
                              <th class="col-xs-1"><%= Task.human_attribute_name(:id) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:title) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:description) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:due_date) %></th>
                              <th class="col-xs-1"><%= Task.human_attribute_name(:status) %></th>
                              <th class="col-xs-3">Projeto</th>
                              <th class="col-xs-1">Ações</th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @tasks_pending.each do |task| %>
                          <tr>
                            <td><%= task.id %></td>
                            <td><%= task.title %></td>
                            <td><%= task.description %></td>
                            <td><%= I18n.l task.due_date, format: :short %></td>
                            <td><%= task.status %></td>
                            <td><%= task.project.name %></td>
                            <td>
                              <%= link_to task do %>
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                              <% end %>
                              <%= link_to edit_project_task_path(task.project, task) do %>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                              <% end %>
                                  <%= link_to task, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<br>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= model_class.model_name.human.pluralize.titleize %> em andamento
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                      <thead>
                          <tr>
                              <th class="col-xs-1"><%= Task.human_attribute_name(:id) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:title) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:description) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:due_date) %></th>
                              <th class="col-xs-1"><%= Task.human_attribute_name(:status) %></th>
                              <th class="col-xs-3">Projeto</th>
                              <th class="col-xs-1">Ações</th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @tasks_in_progress.each do |task| %>
                          <tr>
                            <td><%= task.id %></td>
                            <td><%= task.title %></td>
                            <td><%= task.description %></td>
                            <td><%= I18n.l task.due_date, format: :short %></td>
                            <td><%= task.status %></td>
                            <td><%= task.project.name %></td>
                            <td>
                              <%= link_to task do %>
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                              <% end %>
                              <%= link_to edit_project_task_path(task.project, task) do %>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                              <% end %>
                                  <%= link_to task, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<br>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= model_class.model_name.human.pluralize.titleize %> concluídas
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                      <thead>
                          <tr>
                              <th class="col-xs-1"><%= Task.human_attribute_name(:id) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:title) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:description) %></th>
                              <th class="col-xs-2"><%= Task.human_attribute_name(:due_date) %></th>
                              <th class="col-xs-1"><%= Task.human_attribute_name(:status) %></th>
                              <th class="col-xs-3">Projeto</th>
                              <th class="col-xs-1">Ações</th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @tasks_done.each do |task| %>
                          <tr>
                            <td><%= task.id %></td>
                            <td><%= task.title %></td>
                            <td><%= task.description %></td>
                            <td><%= I18n.l task.due_date, format: :short %></td>
                            <td><%= task.status %></td>
                            <td><%= task.project.name %></td>
                            <td>
                              <%= link_to task do %>
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                              <% end %>
                              <%= link_to edit_project_task_path(task.project, task) do %>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                              <% end %>
                                  <%= link_to task, method: :delete, data: { confirm: 'Tem certeza?' } do %>
                                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>