config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'index/index'
  get 'demo' => 'index#demo'

  get 'index/test'
  post 'index/test'

  get 'about' => 'index#about', as: :about
  get 'dashboard' => 'index#index', as: :dashboard

  get 'project/:project_id/members' => 'members#index', as: :project_members
  get 'project/:project_id/members/new' => 'members#new', as: :new_project_member
  post 'project/:project_id/members/add' => 'members#add', as: :add_project_member
  delete 'project/:project_id/members/:id/remove' => 'members#destroy', as: :project_remove_member

  post 'members/:member_id/toggle_is_scholar' => 'members#toggle_is_scholar', as: :toggle_is_scholar
  post 'members/:member_id/toggle_is_manager' => 'members#toggle_is_manager', as: :toggle_is_manager

  get 'project/:project_id/tasks' => 'tasks#index', as: :project_task
  get 'project/:project_id/tasks/new' => 'tasks#new', as: :new_project_task
  get 'project/:project_id/tasks/:id/edit' => 'tasks#edit', as: :edit_project_task
  post 'project/:project_id/tasks/create' => 'tasks#create', as: :create_project_task
  delete 'project/:project_id/tasks/:id/remove' => 'tasks#destroy', as: :project_remove_task
  get 'tasks/:id/member/new' => 'tasks#new_member', as: :new_task_member
  post 'tasks/:id/member/:user_id/add' => 'tasks#add_member', as: :add_task_member
  delete 'tasks/:id/member/:member_id/remove' => 'tasks#remove_member', as: :task_remove_member

  delete 'events/:id/user/:user_id/remove' => 'events#remove_user', as: :event_remove_user
  get 'events/:id/user/new' => 'events#new_user', as: :new_event_user
  post 'events/:id/user/:user_id/add' => 'events#add_user', as: :add_event_user

  post 'tasks/:id/add_comment' => 'tasks#add_comment', as: :task_add_comment

  resources :projects
  resources :members
  resources :tasks
  resources :events
  resources :users

  root 'index#index'

end

app/views/layouts/application-bak.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P-Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>P-Manager - Gerenciador de Projetos Universitários</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= favicon_link_tag 'favicon.ico' %>
</head>

<body>

<div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to(image_tag("logo_icon.png", class: "nav-logo") + "P-Manager", root_path, class: "navbar-brand") %>
    </div>
    <!-- /.navbar-header -->

  <% if user_signed_in? %>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <%= link_to destroy_user_session_path do %>
          <i class="fa fa-sign-out fa-fw"></i> Sair
        <% end %>
      </li>
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <!--<li class="sidebar-search">
            <div class="input-group custom-search-form">
              <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                  <i class="fa fa-search"></i>
                                </button>
                            </span>
            </div>
          </li> /-->
          <li class="fa sidebar-nav-welcome">
            <h5><span class="fa fa-comment fa-fw" aria-hidden="true"></span> Bem-vindo, <%= current_user.name.split(' ')[0] %>!</h5>
          </li>
          <li>
            <%= link_to dashboard_path do %>
              <i class="fa fa-home fa-fw"></i> Início
            <% end %>
          </li>

          <li>
            <%= link_to projects_path do %>
              <i class="fa fa-flask fa-fw"></i> Projetos
            <% end %>
          </li>

          <li>
            <%= link_to tasks_path do %>
              <i class="fa fa-tasks fa-fw"></i> Tarefas
            <% end %>
          </li>

          <li>
            <%= link_to events_path do %>
              <i class="fa fa-calendar fa-fw"></i> Eventos
            <% end %>
          </li>

          <li>
            <%= link_to users_path do %>
              <i class="fa fa-users fa-fw"></i> Usuários
            <% end %>
          </li>

          <li>
            <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user fa-fw"></i> Meu Perfil
            <% end %>
          </li>

          <li>
            <%= link_to about_path do %>
              <i class="fa fa-info-circle fa-fw"></i> Sobre
            <% end %>
          </li>

        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
    <% end %>
  </nav>

  <div id="page-wrapper">
    <% if notice %>
      <br />
      <div class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <br />
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>

  </div>
  <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->



</body>

</html>